services:
    web:
        environment:
            TWITTER_LAST_TIMESTAMP: ${TWITTER_LAST_TIMESTAMP}
            NEAR_FUNDING_ACCOUNT: ${NEAR_FUNDING_ACCOUNT}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            PINATA_API_KEY: ${PINATA_API_KEY}
            PINATA_API_SECRET: ${PINATA_API_SECRET}
            PINATA_API_JWT: ${PINATA_API_JWT}
            PINATA_API_GATEWAY: ${PINATA_API_GATEWAY}
            OPENAI_KEY: ${OPENAI_KEY}
            BASE_API_KEY: ${BASE_API_KEY}
            TWITTER_API_KEY: ${TWITTER_API_KEY}
            TWITTER_API_SECRET: ${TWITTER_API_SECRET}
            TWITTER_CLIENT_KEY: ${TWITTER_CLIENT_KEY}
            TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
            TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
            TWITTER_REFRESH_TOKEN: ${TWITTER_REFRESH_TOKEN}
            MPC_PUBLIC_KEY_TESTNET: ${MPC_PUBLIC_KEY_TESTNET}
            MPC_PUBLIC_KEY_MAINNET: ${MPC_PUBLIC_KEY_MAINNET}
            RESTART_PASS: ${RESTART_PASS}
        platform: linux/amd64 # Explicitly set for TDX
        image: mattdlockyer/zoracoin-agent:latest@sha256:59c562552c79485247369abd655a88c185affefa87ec98f6e345abb102617480
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
